### ISSUE TITLE
Update target .NET Framework versions to match those used by SLVS 

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarqube-webclient-dotnet#122]
### Description

This repo is still targeting .NET v4.6. SLVS no longer supports VS2017, and the minimum .NET Framework version we support is now v4.7.2.

Note: upgrading the framework causes four of the tests to fail.

**Comment by rita-sonarsource** [comment]
Fixed by https://github.com/SonarSource/sonarqube-webclient-dotnet/pull/143
