### ISSUE TITLE
NuGet package?

### ISSUE THREAD

**Issue by ptupitsyn** [SonarSource/sonarqube-webclient-dotnet#53]
Am I missing something or there is no NuGet package for this library?

**Comment by duncanp-sonar** [comment]
No, there isn't a NuGet package. This library is used internally by SonarLint for Visual Studio. We don't directly provide support for it, and we don't guarantee that we won't make breaking changes.

The intention was that this library would also be used by the SonarScanner for MSBuild but that hasn't happened, so  in the future we might just merge the code back into the SLVS repo.

**Comment by ptupitsyn** [comment]
@duncanp-sonar thanks for the clarification. So what's the "official" way to interact with Sonar Web API from .NET? Plain HttpClient?

**Comment by duncanp-sonar** [comment]
@ptupitsyn the supported APIs are the web APIs, so any .NET HTTP library would do.
